spring:
  application:
    name: forum-project
  datasource:
    url: jdbc:postgresql://localhost:5432/form
    password: 1427
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true